### ISSUE TITLE
Application was unable to start correctly (0xc000007b). Click OK to close the application

### ISSUE THREAD

**Issue by otmanon** [nepluno/libWetHair#6]
Hi, me again!
The code seems to build without any errors bet when it comes to running it, as soon as the console pops up I get an error saying "application was unable to start correctly 0xc000007b). Click OK to close the application"

Again, I can't help but feel it's because I'm using outdated libraries or that there are dependency prroblems. Is there any way (and I know this is asking a lot considering this project ended 3 years ago) that you could post the version number of the libraries not provided with the code?  Even better (and maybe easier for you) could you post the precompiled library binaries you used ?

Also I'm on windows  10. Is that the same with you?
Thanks
Otman

**Comment by raymondyfei** [comment]
We've switched to using `FetchContent` to manage the dependencies, and this issue should no longer happen. Thanks for the reporting.
