### ISSUE TITLE
Stand alone library?

### ISSUE THREAD

**Issue by plattfot** [nepluno/libWetHair#7]
Hi,

I'm interested to use libWetHair, but the current state where it only constructs an executable is too limited for me. I would like to have a library that I can hook into. What gotchas is there if I where to move the `Core` part to a stand alone library?

The executable (`App`) would also use the library.

Thanks.

**Comment by raymondyfei** [comment]
Hi,

Thanks for your PR. This is a good suggestion. The library is of research code and thus a bit messy. I'm planning to make it more structured when there's extra cycle to work on it.

**Comment by plattfot** [comment]
That's fine, then you don't mind if I continue to extract a library out of this? I'll avoid touching the code, to make it easier for you to restructure it when you have the time.

**Comment by raymondyfei** [comment]
Thank you! Go ahead please.

**Comment by plattfot** [comment]
I just created a PR for this #9.

I said I won't touch the code, but while creating the PR I notice the code does not use any namespaces. Which will make it quite hard to use as a library in larger codebases, as symbols will most likely clash. So I'll do one more PR (if it is ok), where I'll add a namespace for `Core`, which will be `libWetHair` and move the sources around to match the namespace. E.g. instead of `libWetHair/App/ExecutableSimulation.h` uses `#include "MathDefs.h"` it will now use `#include <libWetHair/MathDefs.h>`.

**Comment by plattfot** [comment]
namespace will be `libwethair` and not `libWetHair`, to follow the convention used in the code.

**Comment by raymondyfei** [comment]
Yes. It would be great. PR #9 also looks awesome! Thank you!
